# Generated by Django 6.0.6 on 2026-06-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Parroquia')),
                ('ubicacion', models.CharField(choices=[('NORTE', 'Norte'), ('SUR', 'Sur'), ('ESTE', 'Este'), ('OESTE', 'Oeste')], max_length=10, verbose_name='Ubicación')),
                ('tipo', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], max_length=10, verbose_name='Tipo de Parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Barrio/Ciudadela')),
                ('numero_viviendas', models.PositiveIntegerField(verbose_name='Número de Viviendas')),
                ('numero_parques', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Número de Parques')),
                ('numero_edificios_residenciales', models.PositiveIntegerField(verbose_name='Número de Edificios Residenciales')),
                ('parroquia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrios', to='ordenamiento.parroquia', verbose_name='Parroquia')),
            ],
        ),
        migrations.CreateModel(
            name='PresidenteBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula de Identidad')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='Nickname')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('profesion', models.CharField(max_length=100, verbose_name='Profesión')),
                ('barrio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='ordenamiento.barrio', verbose_name='Barrio')),
            ],
        ),
    ]
