# Generated by Django 6.0.6 on 2026-06-24 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presidentebarrio',
            name='barrio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidentes', to='ordenamiento.barrio', verbose_name='Barrio'),
        ),
    ]
